### ISSUE TITLE
.bak

### ISSUE THREAD

**Issue by 1995parham** [aliir74/CompArchMidterm#1]
uploading .bak files into git not good.

**Comment by aliir74** [comment]
مرسی به خاطر تجربه رو منتقل کردن 😅
علتش چیه ولی؟ 🤔

**Comment by 1995parham** [comment]
این فایل‌ها در هربار اجرا عوض می‌شوند و عموما این تیپ چیزا را روی گیت نمیذارن

**Comment by aliir74** [comment]
ممنون!
